/**
 * Definition for singly-linked list.
  * public class ListNode {
   *     public int val;
    *     public ListNode next;
     *     public ListNode(int val=0, ListNode next=null) {
      *         this.val = val;
       *         this.next = next;
        *     }
         * }
          */
          public class Solution {
              public ListNode AddTwoNumbers(ListNode l1, ListNode l2) {
                      var sum = new Dictionary<int,ListNode>();
                              int count = 0;
                                      while(l1 != null || l2 != null){
                                                  if(l1 != null && l2 != null){
                                                                  sum[count] = new ListNode((l1.val + l2.val),null);
                                                                                  l1 = l1.next;
                                                                                                  l2 = l2.next;
                                                                                                              }
                                                                                                                          else if(l1 != null){
                                                                                                                                          sum[count] = new ListNode(l1.val,null);
                                                                                                                                                          l1 = l1.next;
                                                                                                                                                                      }
                                                                                                                                                                                  else{
                                                                                                                                                                                                  sum[count] = new ListNode(l2.val,null);
                                                                                                                                                                                                                  l2 = l2.next;
                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                          count++;
                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                          bool hold =false;
                                                                                                                                                                                                                                                                  for(int i=0;i<count-1;i++){
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                          sum[i].next = sum[i+1];
                                                                                                                                                                                                                                                                                                      if (hold){
                                                                                                                                                                                                                                                                                                                      sum[i].val++;
                                                                                                                                                                                                                                                                                                                                      hold = false;
                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                              if(sum[i].val >= 10){
                                                                                                                                                                                                                                                                                                                                                                              hold = true;
                                                                                                                                                                                                                                                                                                                                                                                              sum[i].val-=10;
                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                          if (hold){
                                                                                                                                                                                                                                                                                                                                                                                                                                          sum[count-1].val++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                          if(sum[count-1].val >= 10){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          sum[count-1].val-=10;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          sum[count-1].next = new ListNode(1,null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return sum[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
